### ISSUE TITLE
API prefix should be nova-vendor

### ISSUE THREAD

**Issue by evd** [naifalshaye/toggle-switch-field#10]
I think API prefix should start with `/nova-vendor`
Most Nova packages use this prefix for their custom API.

I have complex Nginx config with many location rules and already route url starts with `/nova-api` and `/nova-vendor` to Nova.
Add more locations for each packages make it more complicated.

**Comment by naifalshaye** [comment]
Done :) 

Thanks for addressing the issue.

Enjoy toggling ..

**Comment by evd** [comment]
Thanks for fast fix.
But something wrong. Package updated, but no changes.

I think wrong commit tagged for version 1.2.4
On release page tagged commit 8dc6c74 But this commit 2 month ago Center vertically

**Comment by naifalshaye** [comment]
You welcome.

Try now ?

**Comment by evd** [comment]
Toggle work, thanks :)

**Comment by naifalshaye** [comment]
Great ..
