### ISSUE TITLE
multi ToggleSwitchField not working

### ISSUE THREAD

**Issue by milad777v2** [naifalshaye/toggle-switch-field#3]
hi 
i used     ToggleSwitchField::make(__('Show On Menu'), 'show_on_menu')->default(true)->indexToggle(true),

            ToggleSwitchField::make(__('Show On Footer'), 'show_on_footer')->default(true)->indexToggle(true),

            ToggleSwitchField::make(__('Approved'), 'approved')->default(true)->indexToggle(true),
but true and false from table not work

**Comment by naifalshaye** [comment]
Hi,

Composer update
Make sure current version is  1.1.0
Clear Cache

To show the Toggle Switch in index page no need to set default or indexToggle, It's true by default.

ToggleSwitchField::make(__('Show On Footer'), 'show_on_footer'),
ToggleSwitchField::make(__('Approved'), 'approved'),
