### ISSUE TITLE
Doesn't respect readonly()

### ISSUE THREAD

**Issue by ekazda** [naifalshaye/toggle-switch-field#6]
ToggleSwitchField::make('Subscribe')
                ->readonly()

This code does not work. The toggle switch can still be toggled. I was expecting it to be grayed out in whatever position appropriate based on the incoming data.

**Comment by naifalshaye** [comment]
Hi @ekazda issue is fixed and button can be disabled by now with disabled cursor and gray color.

Sorry for the delay..
