### ISSUE TITLE
Multi toggle not working on index & details

### ISSUE THREAD

**Issue by muhannadja** [naifalshaye/toggle-switch-field#7]
When i put multiple toggles on index page or detail , it only updates the first toggle 

  ToggleSwitchField::make(__('Status'), 'status')
                ->color('#3AB95A')
                ->toggleAlign('center'),
            ToggleSwitchField::make(__('Default'), 'is_default')
                ->color('#3AB95A')
                ->toggleAlign('center'),

**Comment by naifalshaye** [comment]
Hi @XYZ19991 issue is fixed, now it allow to have multiple toggle switches fields in the same nova resource.

Sorry for the delay ..
