### ISSUE TITLE
Class "Naif\ToggleSwitch\ToggleSwitchField" not found

### ISSUE THREAD

**Issue by almirhodzic** [naifalshaye/toggle-switch-field#9]
I'm using Laravel Nova v4.34.3
my composer:
"php": "^8.2",
        "inertiajs/inertia-laravel": "^1.0",
        "laravel/framework": "^11.9",
        "laravel/nova": "^4.0",
        "laravel/sanctum": "^4.0",
        "laravel/tinker": "^2.9",
        "naif/toggle-switch-field": "^1.1",
        "outl1ne/nova-sortable": "^3.4",
        "tightenco/ziggy": "^2.0"
        
Im my CategoryResource i do:
ToggleSwitchField::make('Toggle','is_visible')
                ->color('#3AB95A')
                ->toggleAlign('center')
                ->indexToggle(false)
                ->detailToggle(false),

But there says: Class "Naif\ToggleSwitch\ToggleSwitchField" not found

Any knowings about?

**Comment by naifalshaye** [comment]
Hi @almirhodzic try running:

composer dumpautoload
php artisan cache:clear

**Comment by almirhodzic** [comment]
> Hi @almirhodzic try running:
> 
> composer dumpautoload php artisan cache:clear

Ni Naif
<img width="446" alt="Bildschirmfoto 2024-07-13 um 17 10 38" src="https://github.com/user-attachments/assets/767b007c-4c10-4b7c-b2f9-220f2cc94aa0">

Still not found the Class :/

Solved:
Please use "use Naif\ToggleSwitchField\ToggleSwitchField;" instead "use Naif\ToggleSwitch\ToggleSwitchField" this works :)

Thank you anyway :) Great Extension!

**Comment by naifalshaye** [comment]
Hi @almirhodzic 
Try deleting vendor folder and composer.lock and try again
Compose install
